version: '3'

services:
  frontend:
    # web
    container_name: Andromeda_front
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      #args:
      #- NODE_ENV=integration
    ports:
      - 3000:3000
    networks:
      - network-backend

networks:
  network-backend:
    driver: bridge